DROP TABLE IF EXISTS PESQUISA_CIENTIFICA;
CREATE TABLE PESQUISA_CIENTIFICA (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(250) NOT NULL,
  PDF VARCHAR(250) NOT NULL,
  IS_PRIVATE BOOLEAN,
  ATIVA BOOLEAN,
  COMENTARIO VARCHAR(500) NOT NULL
);


INSERT INTO PESQUISA_CIENTIFICA (NOME, PDF, IS_PRIVATE, COMENTARIO) VALUES
  ('Pesquisa1', 'www.googledocs.com/pesquisa1', TRUE, 'Vai custar 2500'),
  ('Pesquisa2', 'www.dropbox.com/pesquisa2', FALSE,'Precisa 2 pregos e 2 tabuas de madeira');
